services:
  redis:
    command: redis-server --save 60 1 --loglevel warning /usr/local/etc/redis/redis.conf
    image: 'redis:7'
    ports:
      - '6379:6379'
    volumes:
        - $PWD/redis-data:/data
        - $PWD/redis-conf:/usr/local/etc/redis:rw
