services:
  redis:
    command: redis-server /usr/local/etc/redis/redis.conf --save 60 1 --loglevel warning
    image: 'redis:7'
    ports:
      - '6379:6379'
    restart: on-failure
    volumes:
        - $PWD/redis-data:/data
        - $PWD/redis-conf:/usr/local/etc/redis:rw
